name: whisper_journal
description: Privacy-first, on-device personal data vault with zero-knowledge encryption
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Local Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Encryption & Security
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  
  # Media & Documents
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  permission_handler: ^11.1.0
  
  # Voice Recording & Transcription
  # record: ^5.1.2  # Temporarily disabled due to platform compatibility
  path_provider_platform_interface: ^2.1.1
  
  # Search
  fuzzywuzzy: ^1.1.6
  
  # UI & Animations
  flutter_animate: ^4.3.0
  glassmorphism_ui: ^0.3.0
  cupertino_icons: ^1.0.6
  
  # Utilities
  uuid: ^4.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  drift_dev: ^2.14.1
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
